### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by UlisesGascon** [UlisesGascon/demo.foo#12]
### Todo

- [x] Make the Docker image public
- [x] Make this repo public
- [x] Merge #11 
- [x] Publish release 1.1.6
- [x] Remove legacy deployments in K8s
